-- Task 1: Create database
-- CREATE DATABASE online_shop;
-- Task 2 + 3: Create database
-- CREATE TABLE products(
--     name VARCHAR(200),
--     price NUMERIC(10, 2),
--     description TEXT,
--     amount_in_stock SMALLINT,
--     image VARCHAR(500)
-- );
-- Task 4: Insert data
-- INSERT INTO
--     products (name, price, description, amount_in_stock, image)
-- VALUES
--     (
--         'A book',
--         12.99,
--         'A really good book',
--         10,
--         'uploads/images/products/a-book.jpg'
--     );
-- Task 5: Update table - add constraints
-- ALTER TABLE
--     products
-- ALTER COLUMN
--     name
-- SET
--     NOT NULL,
-- ALTER COLUMN
--     price
-- SET
--     NOT NULL,
-- ALTER COLUMN
--     description
-- SET
--     NOT NULL,
-- ALTER COLUMN
--     amount_in_stock
-- SET
--     NOT NULL,
-- ADD
--     CONSTRAINT price_positive CHECK (price > 0),
-- ADD
--     CONSTRAINT amount_in_stock_positive CHECK (amount_in_stock > 0)
-- Task 6: Add id column
ALTER TABLE
    products
ADD
    COLUMN id SERIAL PRIMARY KEY